# Generated by Django 5.1.1 on 2025-03-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
